name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  PWA:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: buildAndDeploy
        uses: JamesIves/github-pages-deploy-action@master 
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist/pwa
          BUILD_SCRIPT: npm install && npm run build:pwa
          CLEAN: true
